version: '3.8'

services:
  database:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pokeapp
    networks:
      - backend
  server:
    build:
      context: ./ 
      dockerfile: Dockerfile
    ports:
      - "9999:9999" 
    links:
      - database
    networks:
      - backend
      

#run in a single red
networks:
  backend:
